const API = window.ADMIN_API_BASE_URL || 'http://localhost:8080/api';
let token;
const $ = id => document.getElementById(id);
async function call(path, options = {}) { const response = await fetch(`${API}${path}`, { ...options, headers: { 'content-type': 'application/json', authorization: `Bearer ${token}`, ...(options.headers || {}) } }); if (!response.ok) throw new Error((await response.json()).error || 'خطای API'); return response.status === 204 ? null : response.json(); }
async function refresh() { const [products, categories, orders, users] = await Promise.all([call('/admin/products'), call('/admin/categories'), call('/admin/orders'), call('/admin/users')]); $('products').innerHTML = products.data.map(item => `<div class="row"><span>${item.name} | ${item.price}</span><button data-delete-product="${item.id}">غیرفعال‌سازی</button></div>`).join(''); $('categories').innerHTML = categories.data.map(item => `<div class="row"><span>${item.name}</span><button data-delete-category="${item.id}">غیرفعال‌سازی</button></div>`).join(''); $('orders').innerHTML = orders.data.map(item => `<div class="row"><span>${item.email} | ${item.total_price}</span><select data-order="${item.id}"><option value="new">جدید</option><option value="reviewing">در حال بررسی</option><option value="shipping">در حال ارسال</option><option value="completed">تکمیل شده</option><option value="cancelled">لغو شده</option></select></div>`).join(''); $('users').innerHTML = users.data.map(item => `<div class="row"><span>${item.email}</span><button data-user="${item.id}" data-active="${!item.is_active}">${item.is_active ? 'غیرفعال‌سازی' : 'فعال‌سازی'}</button></div>`).join(''); }
$('login').onclick = async () => { try { const response = await fetch(`${API}/auth/admin/login`, { method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify({email: $('email').value, password: $('password').value}) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); token = data.accessToken; $('dashboard').hidden = false; $('message').textContent = 'ورود موفق بود.'; await refresh(); } catch (error) { $('message').textContent = error.message; } };
$('addProduct').onclick = async () => { await call('/admin/products', {method:'POST', body:JSON.stringify({name:$('productName').value, price:Number($('productPrice').value)})}); await refresh(); };
$('addCategory').onclick = async () => { await call('/admin/categories', {method:'POST', body:JSON.stringify({name:$('categoryName').value})}); await refresh(); };
document.body.onclick = async event => { const product = event.target.dataset.deleteProduct; const category = event.target.dataset.deleteCategory; const user = event.target.dataset.user; if (product) await call(`/admin/products/${product}`, {method:'DELETE'}); if (category) await call(`/admin/categories/${category}`, {method:'DELETE'}); if (user) await call(`/admin/users/${user}/status`, {method:'PATCH', body:JSON.stringify({isActive:event.target.dataset.active === 'true'})}); await refresh(); };
document.body.onchange = async event => { if (event.target.dataset.order) { await call(`/admin/orders/${event.target.dataset.order}`, {method:'PATCH', body:JSON.stringify({status:event.target.value})}); await refresh(); } };
